[package]
name = "fat32-pack"
version = "0.1.0"
authors = ["Haochen Gong <1527198893@qq.com>"]  # 感谢宫浩辰
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.1.8"
fat32 = { path = "../fat32" }
rand = "0.8.0"
